server:
 port: 8080
spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/24_08_Spring
  username: root
  password: 
mybatis:
 type-aliases-package: com.example.demo.vo